name: 管理員操作
description: 設定參加人數 / 重置投票
title: "Admin: <action>"
labels: ["admin"]
body:
  - type: dropdown
    id: action
    attributes:
      label: 操作
      options:
        - set_participants
        - reset_votes
    validations:
      required: true

  - type: input
    id: total_participants
    attributes:
      label: 參加人數（set_participants 必填）
      placeholder: "20"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        注意：reset_votes 會清空所有投票與票數統計。
admin.yml
